### ISSUE TITLE
Unable to catch an error if an import has errors

### ISSUE THREAD

**Issue by danielcardoso5** [bingnz/gulp-less-changed#30]
If one of the imports has an error I see the console.log output of the error ('Failed to process imports for...') but I'm unable to catch the error thrown using the .on("error", handleError) callback.
I can catch an error if the error is thrown in the file that makes the imports.

**Comment by bingnz** [comment]
Hi Daniel,
Does the Less compiler itself fail as well, or just gulp-less-changed? I think I deliberately made the plugin swallow errors otherwise they both report the same problem; the idea being that if the Less doesn't compile then Less itself should tell you. If it's just the plugin, can you find a minimal reproduction of the bug?

**Comment by danielcardoso5** [comment]
Hi David,
the less compiler doesn't fail, I think that since gulp-less-changed doesn't throw an error, the file with errors doesn't get passed through the less compiler. That's happening because the error is on an imported file, if the error is on one of the files that gets compiled it gets passed through.

**Comment by bingnz** [comment]
Imported files don't normally get passed through the pipeline by themselves anyway though; they are read in by the less compiler because they're imported into files that _do_ go through the pipeline. If there's an error then less should fail even in the absence of gulp-less-changed.
The result of an error in processing an import with an error should be that the file is always considered to have changed by gulp-less-changed.
So the question is, do you get the error even if gulp-less-changed is out of the picture? If you don't, then gulp-less-changed needs to be fixed. If you do, I'm not sure what behaviour you're expecting. What I would expect is that less fails to compile the file if there's a bug in the import and that gulp-less-changed will always behave as if the file has changed (in other words it'll try and compile every time even if you haven't changed any files). In this case it logs an error to the output and carries on because less itself should fail and allow you to catch the error later on.
It might help if you have an example I can look at?

**Comment by danielcardoso5** [comment]
Hi David, yes, imported files don't get passed through, but if they have an error, the file that contains that import is not getting through the pipeline. If I remove gulp-less-changed then gulp-less catches the error. What happens is that gulp-less-changed is not allowing the file that has imports with errors to pass through, at least in my build. I'll leave here some part of the code of my task, I can then setup a small example for you to test.

```
gulp
      .src(paths.less_to_compile, { allowEmpty: true })
      .pipe(
        lessChanged({
          getOutputFileName: function(file) {
            return ren(file, {
              dirname: paths.build,
              extname: ".css"
            });
          }
        })
      )
      .pipe(
        print(function(filepath) {
          return "Changed LESS: " + filepath;
        })
      )
      .pipe(
        less({
          modifyVars: {
            "static-root": '"' + args.staticRoot + '"'
          }
        })
      )
```

My `paths.less_to_compile` is just an array of less files that are basically files that contain imports. 
If one of the imports in one of those files has an error, I'm not getting the print after the gulp-less-changed part, which means that gulp-less-changed didn't allow the file to go through.

**Comment by bingnz** [comment]
Hi @danielcardoso5, I thought I'd take a look at this since I hadn't seen your repro and I _think_ I know what you meant. I'm going to release a change so that errors that occur when processing imports are propagated. This might have some side effects for other users of this plugin and if it does I might have to be more specific about which errors are propagated.
